# Generated by Django 4.2.1 on 2023-06-03 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_record_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of data to generate'),
        ),
    ]
